require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/importations', type: :request do
  # Importation. As you add validations to Importation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { content: fixture_file_upload('spec/fixtures/files/cnab.txt', 'text/plain') } }
  let(:invalid_attributes) { { content: '' } }

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_importation_url
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Importation' do
        expect do
          post importations_url, params: { importation: valid_attributes }
        end.to change(Importation, :count).by(1)
      end

      it 'redirects to the stores index' do
        post importations_url, params: { importation: valid_attributes }
        expect(response).to redirect_to(stores_path)
      end

      it 'runs the importation job' do
        allow(ImportationJob).to receive(:perform_later)

        post importations_url, params: { importation: valid_attributes }

        expect(ImportationJob).to have_received(:perform_later)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Importation' do
        expect do
          post importations_url, params: { importation: invalid_attributes }
        end.to change(Importation, :count).by(0)
      end

      it "renders a error response (i.e. to display the 'new' template)" do
        post importations_url, params: { importation: invalid_attributes }
        expect(response).not_to be_successful
      end
    end
  end
end
