name: rails

on:
  push:
    branches: '*'
  pull_request:
    branches:  '*'

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      env:
        RAILS_ENV: 'test'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.3'

    - name: Run Install
      run: |
        bundle install
    - name: Setup database
      run: |
        bundle exec rails db:create db:migrate
    - name: Run Tests (rspec)
      run: |
        bundle exec rspec
